zhaozg/lua-openssl

test/0.tcp.lua
test/0.tcp_c.lua
test/0.tcp_s.lua
test/8.bio_c.lua
test/8.bio_s.lua
test/8.ssl.lua
test/8.ssl_c.lua
test/8.ssl_s.lua

Fix. Tests return 0 in case of success.
Fix. 8. bio/ssl tests pass incorrect type to format function.
All tests pass on WinXP/OpenSSL 1.0.2/lluv 0.1.0
The reason to return `0` as exit code is because if lua occure error in file it also return `1`.
Also this code is not correct
```lua
local _,uv = pcall(require,'luv') -- uv here is library or error message so it always true
...
if uv then
```
Correct for example is
```lua
local ok, uv = pcall(require, 'luv')
if not ok then uv = nil end
...
if uv then
```
Also did you think to install luarocks on travis. This allows you install lluv.
I can PR with my scripts for [travis](https://github.com/moteus/lua-travis-example).

Change. Use lua-lluv to run tests instead of luv.

---

ldoc/openssl.lua
src/openssl.c

Also this function does not clear error queue by default.
For now I have no strong opinion but I think there should be way to
get all errors. Because of current `error` function already have boolean argument to print
error to stderr I think it not very usable to adds one more optional boolen argument to it.
```Lua
-- print all errors
while true do
local no, reason = ssl.last_error()
if not no then break end
print(reason)
end
-- Get only last error and clear error queue
local err, msg = ssl.last_error(true)
```

Add. `last_error` function that returns error separated by part.

---

src/pkey.c

The verify could return a -1 for an error and return 'true' to lua.

double check the return on EVP_verifyFinal

---

src/openssl.c

In the presence of leading zeroes in the hex, produce correct zero padding
in the resulting binary buffer.

correctly convert from hex to binary

---

src/ec.c
src/pkey.c
test/ec.lua
test/rsa.lua
test/test.lua

* The ec key support returned the group values as a table with uppercase key names.
* The other pkey implementations return a lowercase key.
* The curve parameters are p, a and b. Renamed the key names.
* Adds test for ec keys.
* Displays error if the pkey encrypt/decrypt function is used with a not suitable key

Minor fix: Changed ec group parameters to lowercase and fixed naming of curve parameters

---

lib/ssl.lua

pass an int mask instead of unpacked table to ctx:verify_mode
to better comply with the expectations of ssl.c::openssl_ssl_ctx_verify_mode

looks like ctx:verify_mode expects an int mask

---

src/csr.c
src/lbn.c
src/openssl.c

* CSR sign method leaks a public key in a couple of places
* The use of a static BN ctx causes problems with spinning threads for long operations (BN ctx is not thread safe). While you support threading I would guess that BN operations that use the ctx would fail with nasty symptoms (and it leaks)
* Added an optional length parameter to random_load to allow use with /dev.urandom without waiting for ages.

memory leaks, threading issues and a little feature addition

---

src/x509.c

lua_tostring converts numbers so both if's succeed with obvious problems. No point in checking both anyway.

fix time setting.

---

src/asn1.c

I was getting "need asn1_string type mismatch" errors with times. Since the two time types can be used this solved the problem.

ASN1_GENERALIZEDTIME and ASN1_UTCTIME can be used interchangably

---

src/ssl.c

Implemented support for OPENSSL_NO_SSL3 flag + updated the error message to line up with current implementation.  As the default was already TLSv1

Support for OPENSSL_NO_SSL3 flag

---

.travis.yml
deps/lua-compat/c-api/compat-5.3.h

luaL_newlibtable & luaL_newlib has been defined in the following commit:
https://github.com/LuaJIT/LuaJIT/commit/de97b9d52bbc42effeaf1180764053a912526873

Compatible to LuaJIT 2.1

---

src/ssl.c

When a string is passed to ssl_ctx:use as a certificate, use SSL_CTX_use_certificate_chain_file. This should close #121.
Please have a review.

A way to use SSL_CTX_use_certificate_chain_file

---

src/ssl.c

broken error messages currently only print:
```
ssl.lua:20: #1:default is TLSv1 not supported
Maybe [SSLv3] SSLv23 TLSv1 TLSv1_1 TLSv1_2 DTLSv1 [SSLv2], option followed by _client or _server
```

fix error messages

---

src/openssl.c

Added some *free() and *cleanup() functions and changed order.
Fixed all valgrind memoryleaks in libssl for me.
Tested on 1.0 and 1.1.

Modified ssl library cleanup code, fixed all valgrind memoryleaks in libssl

---

Makefile
src/asn1.c
src/bio.c
src/cms.c
src/crl.c
src/lhash.c
src/openssl.c
src/pkey.c
src/ssl.c
src/th-lock.c
src/xattrs.c
src/xname.c

Still needs more work in src/th-lock.c since some functions have been replaced and the old ones don't pop up as deprecated. Can't / don't have time to deal with that right now.
Tested on Raspberry PI Zero W with OpenSSL 1.1.0f and Lua 5.3.3.
Compiles successfully, but basically no runtime testing done.

Removed deprecated OpenSSL functions

---

src/bio.c
src/cipher.c
src/cms.c
src/crl.c
src/dh.c
src/dsa.c
src/ec.c
src/engine.c
src/openssl.c
src/pkey.c
src/rsa.c
src/ssl.c
src/x509.c

When disabling deprecated APIs in OpenSSL, a lot more shows up than the warnings.

Get rid of deprecated APIs

---

lib/crypto.lua

According to http://mkottman.github.io/luacrypto/manual.html raw defaults to false, just like in openssl.digest.digest.

Latest LuaCrypto had raw defaulting to false.

---

src/digest.c

This treats digest:final(nil, true) as digest:final("", true) instead of
ignoring the boolean.

Improve compatibility with LuaCrypto.

---

Makefile.win

closes #212 
Compare with: https://github.com/zhaozg/lua-openssl/commit/5d30d8efa342601d20faf88ba6b10922d75f5a01#diff-af3b638bc2a3e6c650974192a53c7291R25

Link crypt32.lib in makefile.win

---

src/x509.c

For the IP and registered IO cases, push_general_name pushes an
additional table onto the stack causing the tables representing the
general names to become increasingly nested.

Removes additional table allocation in push_general_name

---

src/hmac.c

The original document failed to mention the `raw` parameter and describe the result as a 'binary string' while it is actually a hex encoded binary buffer. This PR is intended to fix that.

fix document to openssl.hmac.hmac in hmac.c

---

src/x509.c

The original loop effectively removed every other extension instead of removing them all, which in turn could result in duplicates when editing extensions.

Fix X.509 extension cleanup order in the OpenSSL 1.1 code variant

---

src/pkey.c
test/4.pkey.lua

chore: more flexible key:is_private()

---

src/ocsp.c

GCC 14 fails to compile the library because -Wincompatible-pointer-types is now fatal. Since the warning is already disabled for clang here, might as well include GCC also. Needless to say, this is a workaround and a proper fix would require upstream changes.

Selectively disable GCC diagnostics in ocsp.c
